    <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">PMS</a>
            </div>
            <div id="navbar" class="collapse navbar-collapse">
				<!-- Authentication Links -->
				@if (!Auth::guest())
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Projects<span class="caret"></span></a>
                        <ul id="app_navi" class="dropdown-menu" role="menu">
                        <li{!! Request::is('projects*') ? ' class="active"' : '' !!}><a href="/projects/">Project</a></li>{{-- generated by scaffold - Project --}}
                        <li{!! Request::is('tasks*') ? ' class="active"' : '' !!}><a href="/tasks/">Task</a></li>{{-- generated by scaffold - Task --}}
                        <li{!! Request::is('appleTypes*') ? ' class="active"' : '' !!}><a href="/appleTypes/">AppleType</a></li>{{-- generated by scaffold - AppleType --}}
                        <li{!! Request::is('apples*') ? ' class="active"' : '' !!}><a href="/apples/">Apple</a></li>{{-- generated by scaffold - Apple --}}
                        </ul>
                       
                        
                    </li>

                </ul>
                 @endif
                  <!-- Right Side Of Navbar -->
                <ul class="nav navbar-nav navbar-right">
                    <!-- Authentication Links -->
                    @if (Auth::guest())
                        <li><a href="{{ url('/login') }}">Login</a></li>
                        <li><a href="{{ url('/register') }}">Register</a></li>
                    @else
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>

                            <ul class="dropdown-menu" role="menu">
                                <li><a href="{{ url('/logout') }}"><i class="fa fa-btn fa-sign-out"></i>Logout</a></li>
                            </ul>
                        </li>
                    @endif
                </ul>
            
            
            </div><!--/.nav-collapse -->
        </div>
    </nav>
