<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/



Route::group(['middleware' => ['web']], function () {
	
	Route::get('/', function () {
		return view('welcome');
	});

	Route::auth();

	Route::get('/home', 'HomeController@index');

    Route::resource("projects","ProjectsController");// generated by scaffold - Project
    Route::get("projects/project/{projects}/duplicate", ['as' => 'projects.duplicate', 'uses' => 'ProjectsController@duplicate']);// generated by scaffold - Project
    Route::resource("tasks","TasksController");// generated by scaffold - Task
    Route::get("tasks/task/{tasks}/duplicate", ['as' => 'tasks.duplicate', 'uses' => 'TasksController@duplicate']);// generated by scaffold - Task
    Route::resource("appleTypes","AppleTypesController");// generated by scaffold - AppleType
    Route::get("appleTypes/appleType/{appleTypes}/duplicate", ['as' => 'appleTypes.duplicate', 'uses' => 'AppleTypesController@duplicate']);// generated by scaffold - AppleType
    Route::resource("apples","ApplesController");// generated by scaffold - Apple
    Route::get("apples/apple/{apples}/duplicate", ['as' => 'apples.duplicate', 'uses' => 'ApplesController@duplicate']);// generated by scaffold - Apple
    
    Route::get("test","TasksController@test"); // 
    Route::post("test",  
  ['as' => 'test.store', 'uses' => "TasksController@test"]); // 
});
