<?php

use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // $this->call(UsersTableSeeder::class);
        $this->call(ProjectsTableSeeder::class);// generated by scaffold - Project
        $this->call(TasksTableSeeder::class);// generated by scaffold - Task
        $this->call(TasksTableSeeder::class);// generated by scaffold - Task
        $this->call(AppleTypesTableSeeder::class);// generated by scaffold - AppleType
        $this->call(ApplesTableSeeder::class);// generated by scaffold - Apple
    }
}
