<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use dogears\CrudDscaffold\Traits\GetAllDataTrait;
use dogears\CrudDscaffold\Traits\RelationManagerTrait;

class AppleType extends Model
{
    use RelationManagerTrait,GetAllDataTrait;

    public function __construct(array $attributes = array())
    {
        parent::__construct($attributes);
    } 

	//Mass Assignment
	protected $fillable = ['name'];

	// generated by relation command - AppleType,Apple - start
	public function apples() {
		return $this->hasMany('App\Apple');
	}// end
}