<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use dogears\CrudDscaffold\Traits\GetAllDataTrait;
use dogears\CrudDscaffold\Traits\RelationManagerTrait;

class Apple extends Model
{
    use RelationManagerTrait,GetAllDataTrait;

    public function __construct(array $attributes = array())
    {
        parent::__construct($attributes);
		$this->addRelationApp( new \App\AppleType, 'name' );  // generated by relation command - AppleType,Apple
    } 

	//Mass Assignment
	protected $fillable = ['name','apple_type_id'];

	// generated by relation command - AppleType,Apple - start
	public function appleType() {
		return $this->belongsTo('App\AppleType');
	}// end
}