<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use dogears\CrudDscaffold\Traits\GetAllDataTrait;
use dogears\CrudDscaffold\Traits\RelationManagerTrait;

class Project extends Model
{
    use RelationManagerTrait,GetAllDataTrait;

    public function __construct(array $attributes = array())
    {
        parent::__construct($attributes);
    } 

	//Mass Assignment
	protected $fillable = ['parent_id','name','description'];

	// generated by relation command - Project,Task - start
	public function tasks() {
		return $this->hasMany('App\Task');
	}// end
}