<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use dogears\CrudDscaffold\Traits\GetAllDataTrait;
use dogears\CrudDscaffold\Traits\RelationManagerTrait;

class Task extends Model
{
    use RelationManagerTrait,GetAllDataTrait;

    public function __construct(array $attributes = array())
    {
        parent::__construct($attributes);
		$this->addRelationApp( new \App\Project, 'name' );  // generated by relation command - Project,Task
    } 

	//Mass Assignment
	protected $fillable = ['parent_id','project_id','name','description'];

	// generated by relation command - Project,Task - start
	public function project() {
		return $this->belongsTo('App\Project');
	}// end
}
